### ISSUE TITLE
pasting with no-hooks creates unnecessary closing characters

### ISSUE THREAD

**Issue by basbebe** [alexherbo2/auto-pairs.kak#46] opened 2021-02-19 14:59 UTC
If I insert something from the system clipboard which has parantheses (or other pairs), I will get redundant closing characters at the end of my paste.

- copy some code with parantheses
- go to insert mode with `no-hooks`: `\i`
- `CTRL-V` or `CMD-V` or whatever your system / terminal supports
- => extra parentheses

**Comment by alexherbo2** [comment] 2021-02-19 17:56
The plugin is currently broken because you cannot disable mappings.

See [#3599] and [#3600].

[#3599]: https://github.com/mawww/kakoune/issues/3599
[#3600]: https://github.com/mawww/kakoune/issues/3600

**Comment by maximbaz** [comment] 2023-08-03 13:26
Closing as fixed, I also can't reproduce now.

**Closed by maximbaz** 2023-08-03 13:26 UTC
